name: habits_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  file_picker: ^6.1.1
  share_plus: ^7.2.0
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/splash/
    - assets/icons/
    - assets/backgrounds/

flutter_native_splash:
  color: "#F8E1B5"
  image: assets/splash/splash.png
  android: true
  ios: true
  android_12:
    color: "#F8E1B5"
    image: assets/splash/splash.png

