name: habits_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  file_picker: ^10.3.7
  share_plus: ^12.0.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#F8E1B5"
  image: assets/splash/karo_splash.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/splash/karo_splash.png

